### PR TITLE
FIX(non-file-null): added a few better cleanups

### LINKED ISSUE #27: [BUG] BUG-14: File handle leak in pars_isFileValid — fopen'd file never closed on wrong extension
## Summary

`pars_isFileValid` opens the file with `fopen` before validating the extension. If the file exists but has a wrong extension (not `.lo3`), the function returns `-1` without calling `fclose`. One file descriptor is leaked on every invalid-extension run.

## Affected file

`src/parsing.c`, lines 14–30

```c
*file = fopen(name, "r");      // opens the file
if (*file == NULL) return -1;

if (strcmp(&name[len - 4], ".lo3") != 0) {
    lo3_error("File must end with .lo3\n", name);
    return -1;  // ← file is open but never closed
}
```

## Suggested fix

Close the file before returning on the extension error:

```c
if (strcmp(&name[len - 4], ".lo3") != 0) {
    fclose(*file);
    *file = NULL;
    lo3_error("File must end with .lo3\n", name);
    return -1;
}
```

---
*This issue was identified and created by [Claude](https://claude.ai) on behalf of the repository maintainer.*

### PR DESCRIPTION
**Pull request by seesee010**

### CODE REVIEW

File: src/main.c [hunk 1]
```diff
@@ -1,9 +1,10 @@
 // Copyright (c) 2026 seesee010
 // Read the License file for more informations about the license.
 
+#include "./internal/cf-define.h"
 #include "./internal/core.h"
 #include "internal/bare-var.h"
-#include "./internal/cf-define.h"
+#include <stdio.h>
```
Comment (seesee010) [inline src/main.c:7]: lib <stdio.h> is already in another inlcude !!!.
Delete it.

File: src/parsing.c [hunk 2]
```diff
@@ -136,8 +136,7 @@ lo3_val pars_resv(char type[64]) {
 	switch (result.type) {
 
 	// find the corresponding type
-	case TYPE_num:
-	{
+	case TYPE_num: {
```
Comment (seesee010) [inline src/parsing.c]: is not that worse

File: src/parsing.c [hunk 3]
```diff
@@ -153,8 +152,7 @@ lo3_val pars_resv(char type[64]) {
 		break;
 	}
 
-	case TYPE_array:
-	{
+	case TYPE_array: {
```
Comment (seesee010) [inline src/parsing.c]: is not that worse
